# Generated by Django 4.2.6 on 2023-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
